<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "dokter".
 *
 * @property integer $id
 * @property string $nama_dokter
 * @property string $spesialis
 * @property string $alamat
 * @property string $telepon
 * @property string $priv
 * @property integer $id_user
 * @property string $aliasModel
 */
abstract class Dokter extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'dokter';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['nama_dokter', 'spesialis', 'alamat', 'telepon', 'priv'], 'required'],
            [['id_user'], 'integer'],
            [['nama_dokter', 'spesialis', 'alamat', 'telepon', 'priv'], 'string', 'max' => 200]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nama_dokter' => 'Nama Dokter',
            'spesialis' => 'Spesialis',
            'alamat' => 'Alamat',
            'telepon' => 'Telepon',
            'priv' => 'Priv',
            'id_user' => 'Id User',
        ];
    }




}
