<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "pasien".
 *
 * @property integer $id
 * @property string $nama_pasien
 * @property string $jenis_kelamin
 * @property string $ttl
 * @property string $status_perkawinan
 * @property string $alamat_pasien
 * @property string $telepon
 * @property string $tanggal
 * @property string $aliasModel
 */
abstract class Pasien extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'pasien';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['nama_pasien', 'jenis_kelamin', 'ttl', 'status_perkawinan', 'alamat_pasien', 'telepon', 'tanggal'], 'required'],
            [['tanggal'], 'safe'],
            [['nama_pasien', 'alamat_pasien'], 'string', 'max' => 200],
            [['jenis_kelamin', 'ttl', 'status_perkawinan'], 'string', 'max' => 100],
            [['telepon'], 'string', 'max' => 12]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nama_pasien' => 'Nama Pasien',
            'jenis_kelamin' => 'Jenis Kelamin',
            'ttl' => 'Ttl',
            'status_perkawinan' => 'Status Perkawinan',
            'alamat_pasien' => 'Alamat Pasien',
            'telepon' => 'Telepon',
            'tanggal' => 'Tanggal',
        ];
    }




}
