<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "rumah_sakit".
 *
 * @property integer $id
 * @property string $kode
 * @property string $nama_faskes
 * @property string $tipe_faskes
 * @property string $alamat
 * @property string $aliasModel
 */
abstract class RumahSakit extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'rumah_sakit';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['kode', 'nama_faskes', 'tipe_faskes', 'alamat'], 'required'],
            [['kode', 'nama_faskes', 'tipe_faskes', 'alamat'], 'string', 'max' => 200]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'kode' => 'Kode',
            'nama_faskes' => 'Nama Faskes',
            'tipe_faskes' => 'Tipe Faskes',
            'alamat' => 'Alamat',
        ];
    }




}
